CREATE DATABASE QLSTK
GO
USE QLSTK
GO

CREATE TABLE LOAITIETKIEM
(
	MaLoaiTietKiem VARCHAR(20) NOT NULL PRIMARY KEY,
	TenLoaiTietKiem NVARCHAR(50) NOT NULL,
	KyHan INT NOT NULL,
	LaiSuat FLOAT NOT NULL CHECK(LaiSuat>0),
	ThoiGianGuiToiThieu INT NOT NULL CHECK(ThoiGianGuiToiThieu>0),
	--Doi ten tu SoTienDuocRut va sua thanh Nvarchar de hien thi bang loai tiet kiem
	QuyDinhSoTienRut NVARCHAR(50) NOT NULL,
	---Them DangSuDung de xoa 1 loai tiet kiem, thuc ra la chuyen no ve khong su dung nua de khong bi loi du lieu ay
	DangSuDung INT NOT NULL,
)
GO

CREATE TABLE SOTIETKIEM
(
	MaSoTietKiem VARCHAR(20) NOT NULL PRIMARY KEY,
	MaLoaiTietKiem VARCHAR(20) NOT NULL FOREIGN KEY REFERENCES LOAITIETKIEM(MaLoaiTietKiem),
	TenKhachHang NVARCHAR(50) NOT NULL,
	DiaChi NVARCHAR(MAX) NOT NULL, 
	SoTienGuiBanDau MONEY NOT NULL CHECK(SoTienGuiBanDau>0),
	SoCMND VARCHAR(20) NOT NULL,
	NgayMoSo SMALLDATETIME NOT NULL,
	LaiSuatApDung FLOAT NOT NULL CHECK (LaiSuatApDung>0), 
	NgayDaoHanKeTiep SMALLDATETIME NOT NULL,
	SoDu MONEY NOT NULL CHECK (SoDu>=0), 
	NgayDongSo SMALLDATETIME,
)
GO
ALTER TABLE SOTIETKIEM ADD CHECK(DATEDIFF(DAYOFYEAR,NgayMoSo,NgayDongSo)>0)
GO

CREATE TABLE PHIEUGUI
(
	MaPhieuGui VARCHAR(20) NOT NULL PRIMARY KEY,
	MaSoTietKiem VARCHAR(20) NOT NULL FOREIGN KEY REFERENCES SOTIETKIEM(MaSoTietKiem),
	NgayGui SMALLDATETIME NOT NULL,
	SoTienGui MONEY NOT NULL CHECK (SoTienGui>0)
)
GO

CREATE TABLE PHIEURUT
(
	MaPhieuRut VARCHAR(20) NOT NULL PRIMARY KEY,
	MaSoTietKiem VARCHAR(20) NOT NULL FOREIGN KEY REFERENCES SOTIETKIEM(MaSoTietKiem),
	NgayRut SMALLDATETIME NOT NULL,
	SoTienRut MONEY NOT NULL CHECK (SoTienRut>0)
)
GO

CREATE TABLE BAOCAODOANHSO
(
	MaBaoCaoDoanhSo VARCHAR(20) NOT NULL PRIMARY KEY,
	NgayDoanhSo SMALLDATETIME NOT NULL,
	MaLoaiTietKiem VARCHAR(20) NOT NULL FOREIGN KEY REFERENCES LOAITIETKIEM(MaLoaiTietKiem),
	TongThu MONEY NOT NULL CHECK (TongThu>=0),
	TongChi MONEY NOT NULL CHECK (TongChi>=0),
	ChenhLech MONEY NOT NULL,
)
GO

CREATE TABLE BAOCAOMODONG
(
	MaBaoCaoMoDong VARCHAR(20) NOT NULL PRIMARY KEY,
	MaLoaiTietKiem VARCHAR(20) NOT NULL FOREIGN KEY REFERENCES LOAITIETKIEM(MaLoaiTietKiem),
	ThangBaoCao INT NOT NULL CHECK (ThangBaoCao>=1 AND ThangBaoCao<=12),
	NamBaoCao INT NOT NULL CHECK (NamBaoCao>0),
)
GO

CREATE TABLE CTBCMODONG
(
	MaBaoCaoMoDong VARCHAR(20) NOT NULL FOREIGN KEY REFERENCES BAOCAOMODONG(MaBaoCaoMoDong),
	NgayXet SMALLDATETIME NOT NULL,
	-----Sua lai rang buoc nho hon bang
	SoLuongSoMo INT NOT NULL CHECK (SoLuongSoMo>=0),
	SoLuongSoDong INT NOT NULL CHECK (SoLuongSoDong>=0),
	ChenhLech INT NOT NULL,
	---sua lai khoa chinh la hai thuoc tinh nay
	PRIMARY KEY (MaBaoCaoMoDong,NgayXet)
)
GO

CREATE TABLE THAMSO
(
	TenThamSo VARCHAR(50) NOT NULL PRIMARY KEY,
	GiaTri MONEY NOT NULL
)
GO

----QUAN LI NGUOI DUNG

CREATE TABLE CHUCNANG
(
	MaChucNang INT NOT NULL PRIMARY KEY,
	TenChucNang NVARCHAR(50) NOT NULL,
	TenThanhPhanSuDung NVARCHAR(50) NOT NULL
)
GO

CREATE TABLE NHOMNGUOIDUNG
(
	MaNhom INT NOT NULL PRIMARY KEY,
	TenNhom NVARCHAR(50) NOT NULL
)
GO

CREATE TABLE PHANQUYEN
(
	MaNhom INT NOT NULL FOREIGN KEY REFERENCES NHOMNGUOIDUNG(MaNhom),
	MaChucNang INT NOT NULL FOREIGN KEY REFERENCES CHUCNANG(MaChucNang),
	LiDo NVARCHAR(50),
	PRIMARY KEY(MaNhom,MaChucNang)
)
GO

CREATE TABLE NGUOIDUNG
(
	TenDangNhap VARCHAR(50) NOT NULL PRIMARY KEY,
	MatKhau VARCHAR(50) NOT NULL,
	MaNhom INT NOT NULL FOREIGN KEY REFERENCES NHOMNGUOIDUNG(MaNhom),
	HoTen NVARCHAR(50)
)
GO


