CREATE DATABASE MASTERSAVEDEMODB
GO

USE MASTERSAVEDEMODB
GO

--USE DEMODATA
--DROP DATABASE QLSTK

CREATE TABLE LOAITIETKIEM
(
	MaLoaiTietKiem VARCHAR(20) NOT NULL PRIMARY KEY,
	TenLoaiTietKiem NVARCHAR(50) NOT NULL,
	KyHan INT NOT NULL,
	LaiSuat FLOAT NOT NULL CHECK(LaiSuat>0)
)
GO

CREATE TABLE SOTIETKIEM
(
	MaSoTietKiem VARCHAR(20) NOT NULL PRIMARY KEY,
	MaLoaiTietKiem VARCHAR(20) NOT NULL FOREIGN KEY REFERENCES LOAITIETKIEM(MaLoaiTietKiem),
	TenKhachHang NVARCHAR(50) NOT NULL,
	DiaChi NVARCHAR(MAX) NOT NULL, 
	SoTienGuiBanDau MONEY NOT NULL CHECK(SoTienGuiBanDau>0),
	SoCMND VARCHAR(20) NOT NULL,
	NgayMoSo SMALLDATETIME NOT NULL,
	LaiSuatApDung FLOAT NOT NULL CHECK (LaiSuatApDung>0), 
	SoDu MONEY NOT NULL CHECK (SoDu>=0), 
	TrangThai BIT NOT NULL
)
GO

CREATE TABLE PHIEUGUI
(
	MaPhieuGui VARCHAR(20) NOT NULL PRIMARY KEY,
	MaSoTietKiem VARCHAR(20) NOT NULL FOREIGN KEY REFERENCES SOTIETKIEM(MaSoTietKiem),
	TenKhachHang NVARCHAR(50) NOT NULL,
	NgayGui SMALLDATETIME NOT NULL,
	SoTienGui MONEY NOT NULL CHECK (SoTienGui>0)
)
GO

CREATE TABLE PHIEURUT
(
	MaPhieuRut VARCHAR(20) NOT NULL PRIMARY KEY,
	MaSoTietKiem VARCHAR(20) NOT NULL FOREIGN KEY REFERENCES SOTIETKIEM(MaSoTietKiem),
	TenKhachHang NVARCHAR(50) NOT NULL,
	NgayRut SMALLDATETIME NOT NULL,
	SoTienRut MONEY NOT NULL CHECK (SoTienRut>0)
)
GO

CREATE TABLE BAOCAODOANHSO
(
	MaBaoCaoDoanhSo VARCHAR(20) NOT NULL PRIMARY KEY,
	NgayBaoCao SMALLDATETIME NOT NULL,
	MaLoaiTietKiem VARCHAR(20) NOT NULL FOREIGN KEY REFERENCES LOAITIETKIEM(MaLoaiTietKiem),
	TongThu MONEY NOT NULL CHECK (TongThu>=0),
	TongChi MONEY NOT NULL CHECK (TongChi>=0),
	ChechLechDoanhSo MONEY NOT NULL,
)
GO

CREATE TABLE BAOCAOMODONG
(
	MaBaoCaoMoDong VARCHAR(20) NOT NULL PRIMARY KEY,
	ThangBaoCao INT NOT NULL CHECK (ThangBaoCao>=1 AND ThangBaoCao<=12),
	NamBaoCao INT NOT NULL CHECK (NamBaoCao>0),
)
GO

CREATE TABLE CTBCMODONG
(
	MaBaoCaoMoDong VARCHAR(20) NOT NULL FOREIGN KEY REFERENCES BAOCAOMODONG(MaBaoCaoMoDong),
	MaLoaiTietKiem VARCHAR(20) NOT NULL FOREIGN KEY REFERENCES LOAITIETKIEM(MaLoaiTietKiem),
	NgayXet SMALLDATETIME NOT NULL,
	SoLuongSoMo INT NOT NULL CHECK (SoLuongSoMo>0),
	SoLuongSoDong INT NOT NULL CHECK (SoLuongSoDong>0),
	ChechLechSoLuong INT NOT NULL,
	PRIMARY KEY (MaBaoCaoMoDong, MaLoaiTietKiem)
)
GO

CREATE TABLE THAMSO
(
	TenThamSo VARCHAR(20) NOT NULL PRIMARY KEY,
	GiaTri FLOAT NOT NULL
)
GO

