//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterSaveDemo.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BAOCAOMODONG
    {
        public string MaBaoCaoMoDong { get; set; }
        public string MaLoaiTietKiem { get; set; }
        public int ThangBaoCao { get; set; }
        public int NamBaoCao { get; set; }
    
        public virtual LOAITIETKIEM LOAITIETKIEM { get; set; }
        public virtual CTBCMODONG CTBCMODONG { get; set; }
    }
}
