//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterSaveDemo.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QLSTKEntities : DbContext
    {
        public QLSTKEntities()
            : base("name=QLSTKEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BAOCAODOANHSO> BAOCAODOANHSOes { get; set; }
        public virtual DbSet<BAOCAOMODONG> BAOCAOMODONGs { get; set; }
        public virtual DbSet<CTBCMODONG> CTBCMODONGs { get; set; }
        public virtual DbSet<LOAITIETKIEM> LOAITIETKIEMs { get; set; }
        public virtual DbSet<PHIEUGUI> PHIEUGUIs { get; set; }
        public virtual DbSet<PHIEURUT> PHIEURUTs { get; set; }
        public virtual DbSet<SOTIETKIEM> SOTIETKIEMs { get; set; }
        public virtual DbSet<THAMSO> THAMSOes { get; set; }
        public virtual DbSet<CHUCNANG> CHUCNANGs { get; set; }
        public virtual DbSet<NGUOIDUNG> NGUOIDUNGs { get; set; }
        public virtual DbSet<NHOMNGUOIDUNG> NHOMNGUOIDUNGs { get; set; }
        public virtual DbSet<PHANQUYEN> PHANQUYENs { get; set; }
    }
}
